# This is a workflow that is reused in the post repositories to build each post
# and it doesn't actually get run on this repo.
name: 'Execute blog post'
description: "Sets up and executes each blog post on adrn's blog"

inputs:
  python-version:
    description: "Python version to use"
    default: "3.12"

# Any outputs?
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        clean: false

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install the project
      run: uv sync

    # Run pre-commit:
    - name: Cache pre-commit environments
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-

    - name: Run pre-commit
      shell: bash
      run: uv run pre-commit run --all-files

    - name: Push changes to main
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: main
        folder: "."

    # Execute the post notebook:
    - name: Install custom fonts
      shell: bash
      run: |
        cp -R fonts/Old_Standard_TT /usr/share/fonts/
        fc-cache -fv

    - name: Add custom IPython kernel settings
      shell: bash
      run: |
        mkdir -p ~/.ipython/profile_default
        echo "c.InlineBackend.rc = {}" > ~/.ipython/profile_default/ipython_kernel_config.py

    - name: Execute the post using nbconvert
      shell: bash
      run: uv run jupyter nbconvert --to notebook --output=post.ipynb --execute post.ipynb

    - name: Upload the executed notebook as an artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: executed
        path: post.ipynb

    - name: Push executed notebook to 'executed' branch
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4.6.4
      with:
        branch: executed
        folder: "."
        single-commit: true
        clean: true
