# This is a workflow that is reused in the post repositories to build each post
# and it doesn't actually get run on this repo.
name: 'Execute blog post'
description: "Sets up and executes each blog post on adrn's blog"

inputs:
  python-version:
    type: string
    default: "3.10"

# Any outputs?
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    # Run pre-commit:
    - name: Cache pre-commit environments
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-
    - name: Install pre-commit
      run: python -m pip install -U pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files

    # Freeze dependencies
    - name: Write runtime file
      run: echo "python-${{ inputs.python-version }}" > ./runtime.txt
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.in') }}
        restore-keys: |
          ${{ runner.os }}-deps-
    - name: Install pip-tools
      run: |
        python -m pip install -U pip
        python -m pip install -U pip-tools
    - name: Freeze dependencies
      run: pip-compile
    - name: Upload requirements.txt
      uses: actions/upload-artifact@v3
      with:
        name: requirements
        path: requirements.txt
    - name: Push changes to main
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: main
        folder: "."

    # Execute the post notebook:
    - name: Install Google Fonts
      run: |
        wget -O Old_Standard_TT.zip https://fonts.google.com/download?family=Old%20Standard%20TT
        unzip -d old_standard_tt/ Old_Standard_TT.zip
        mv old_standard_tt /usr/share/fonts/
        fc-cache -fv

    - name: Download the frozen requirements
      uses: actions/download-artifact@v3
      with:
        name: requirements
    - name: Install correct dependencies
      run: pip-sync
    - name: Add custom IPython kernel settings
      run: |
        mkdir -p ~/.ipython/profile_default
        echo "c.InlineBackend.rc = {}" > ~/.ipython/profile_default/ipython_kernel_config.py
    - name: Execute the post using nbconvert
      run: jupyter nbconvert --to notebook --output=post.ipynb --execute post.ipynb
    - name: Upload the executed notebook as an artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: executed
        path: post.ipynb
    - name: Push executed notebook to 'executed' branch
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: executed
        folder: "."
        single-commit: true
        clean: true
